// Mocks generated by Mockito 5.4.4 from annotations
// in online_exam_elevate/test/data/repos/auth/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:online_exam_elevate/core/Result/result.dart' as _i4;
import 'package:online_exam_elevate/data/contracts/auth/online_data_source.dart'
    as _i2;
import 'package:online_exam_elevate/data/models/request/register_request.dart'
    as _i7;
import 'package:online_exam_elevate/domain/entities/user.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthOnlineDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthOnlineDataSource extends _i1.Mock
    implements _i2.AuthOnlineDataSource {
  MockAuthOnlineDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.User?>> login({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #login,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);

  @override
  _i3.Future<_i4.Result<_i5.User?>> register(
          _i7.RegisterRequest? registerRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [registerRequest],
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #register,
            [registerRequest],
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);

  @override
  _i3.Future<_i4.Result<bool>> forgetPassword(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #forgetPassword,
          [email],
        ),
        returnValue:
            _i3.Future<_i4.Result<bool>>.value(_i6.dummyValue<_i4.Result<bool>>(
          this,
          Invocation.method(
            #forgetPassword,
            [email],
          ),
        )),
      ) as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<bool>> verifyResetCode(String? code) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyResetCode,
          [code],
        ),
        returnValue:
            _i3.Future<_i4.Result<bool>>.value(_i6.dummyValue<_i4.Result<bool>>(
          this,
          Invocation.method(
            #verifyResetCode,
            [code],
          ),
        )),
      ) as _i3.Future<_i4.Result<bool>>);

  @override
  _i3.Future<_i4.Result<_i5.User?>> resetPassword({
    required String? email,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #resetPassword,
          [],
          {
            #email: email,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i3.Future<_i4.Result<_i5.User?>>.value(
            _i6.dummyValue<_i4.Result<_i5.User?>>(
          this,
          Invocation.method(
            #resetPassword,
            [],
            {
              #email: email,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i3.Future<_i4.Result<_i5.User?>>);
}
