// Mocks generated by Mockito 5.4.4 from annotations
// in online_exam_elevate/test/presentation/auth/view_model/forget_pass/forget_pass_view_model_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:online_exam_elevate/core/Result/result.dart' as _i4;
import 'package:online_exam_elevate/core/utils/services/cache_service.dart'
    as _i6;
import 'package:online_exam_elevate/domain/usecases/auth/forget_password_usecase.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ForgetPasswordUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgetPasswordUseCase extends _i1.Mock
    implements _i2.ForgetPasswordUseCase {
  MockForgetPasswordUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<bool>> invoke(String? email) => (super.noSuchMethod(
        Invocation.method(
          #invoke,
          [email],
        ),
        returnValue:
            _i3.Future<_i4.Result<bool>>.value(_i5.dummyValue<_i4.Result<bool>>(
          this,
          Invocation.method(
            #invoke,
            [email],
          ),
        )),
      ) as _i3.Future<_i4.Result<bool>>);
}

/// A class which mocks [CacheService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCacheService extends _i1.Mock implements _i6.CacheService {
  MockCacheService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void init() => super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  dynamic getData({required String? key}) =>
      super.noSuchMethod(Invocation.method(
        #getData,
        [],
        {#key: key},
      ));

  @override
  _i3.Future<bool> saveData({
    required String? key,
    required dynamic value,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveData,
          [],
          {
            #key: key,
            #value: value,
          },
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<bool> removeData({required String? key}) => (super.noSuchMethod(
        Invocation.method(
          #removeData,
          [],
          {#key: key},
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}
